### ISSUE TITLE
TMLDecodeError - ColumnPropertiesGeoConfig got an unexpected keyword argument 'geometryType'

### ISSUE THREAD

**Issue by boonhapus** [thoughtspot/thoughtspot_tml#16]
If you configure a searchable object **[with a custom region](https://docs.thoughtspot.com/cloud/latest/geomaps-custom)**, then we get a `TMLDecodeError`.

```python
from thoughtspot_tml.utils import determine_tml_type
from thoughtspot_tml import Table

tml_data = ...  # fetch from metadata/tml/export
tml_cls  = determine_tml_type(info=tml_data["info"])

tml_cls.loads(tml_data["edoc"])
#
#    | thoughtspot_tml.exceptions.TMLDecodeError: ColumnPropertiesGeoConfigProto.__init__() got an unexpected keyword argument 'geometryType'
#    | supplied data does not produce a valid TML (Worksheet) document
```

The **[TML spec details](https://docs.thoughtspot.com/cloud/latest/tml-tables#geometryType)** that the geography config custom geo-json type as `geometryType` instead of `geometry_type`.

```yaml
      geo_config:
        latitude : true
          OR
        longitude : true
          OR
        country : true
          OR
        region_name:
        - country : <name_supported_country>
        - region_name : <region_name_in_UI>
          OR
        custom_file_guid: <custom_map_guid>
        geometryType: <custom_map_geometry_type>
```

We can write another custom serializer for this when generating the `_scriptability.py` spec.

https://github.com/thoughtspot/thoughtspot_tml/blob/fea993a84f53a0004d372c805968c94d19e7f397/_generate/__main__.py#L148-L154

Probably something like..

```python
     if isinstance(attribute, ast.AnnAssign) and attribute.target.id == "geometry_type": 
         attribute.target.id = self.snake_to_camel(attribute.target.id) 
```
