### ISSUE TITLE
[BUG] Incorrect formula ids when special characters are used

### ISSUE THREAD

**Issue by ioanalex** [thoughtspot/thoughtspot_tml#7]
Hi, I use the `cs_tools` scriptability tool to manage TMLs and I see the following behavior when downloading the TML of a worksheet.

The Worksheet has the following formula definition:

```yaml
formulas:
  - id: Capacity Bytes
    name: "Capacity [Bytes]"
    expr: "..."
```

Later on the file we pull this formula as a column of the Worksheet:

```yaml
  worksheet_columns:
  - name: "Capacity [Bytes]"
    formula_id: "Capacity [Bytes]"
```

If I try to `cs_tools tools scriptability import ...` I get the following error:

```
[14:31:33] ERROR    <guid>.worksheet -- Worksheet columns use invalid formula IDs.<br/>- <b>Used [Bytes]</b><br/><ul><li>* Used [Bytes]</li></ul><br/>- <b>Capacity [Bytes]</b><br/><ul><li>*     _import.py:608
                    Capacity [Bytes]</li></ul><br/><b>SOLUTION:</b><br/>Specify correct formula IDs.
```
(there is a `Used [Bytes]` formula too, same as the example I give above)

I was able to fix this issue by using the correct `formula_id` on the `worksheet_column` which is `Capacity Bytes`.

This looks like a problem with the thoughtspot-tml library.
